// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_refresh_token.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_token(
    token,
    created_at,
    updated_at,
    user_id,
    expires_at,
    revoked_at
)
VALUES($1, $2, $3, $4, $5, $6)
`

type InsertRefreshTokenParams struct {
	Token     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    uuid.UUID
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}
