// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_refresh_token.sql

package database

import (
	"context"
)

const getRreshToken = `-- name: GetRreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_token
WHERE token = $1
`

func (q *Queries) GetRreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
