// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_from_refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getuserFromRefreshToken = `-- name: GetuserFromRefreshToken :one
SELECT id, users.created_at, users.updated_at, email, hashed_password, is_chirpy_red, token, refresh_token.created_at, refresh_token.updated_at, user_id, expires_at, revoked_at FROM users
INNER JOIN refresh_token
ON refresh_token.user_id = users.id
WHERE refresh_token.token = $1
`

type GetuserFromRefreshTokenRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          sql.NullString
	HashedPassword string
	IsChirpyRed    sql.NullBool
	Token          string
	CreatedAt_2    sql.NullTime
	UpdatedAt_2    sql.NullTime
	UserID         uuid.UUID
	ExpiresAt      sql.NullTime
	RevokedAt      sql.NullTime
}

func (q *Queries) GetuserFromRefreshToken(ctx context.Context, token string) (GetuserFromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getuserFromRefreshToken, token)
	var i GetuserFromRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
		&i.Token,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
